- app/assets/stylesheets/form.scss
- app/assets/stylesheets/questions.scss
- app/assets/stylesheets/style/mixins/theme/_checkBox.scss
- app/assets/stylesheets/style/mixins/theme/_input.scss
- app/assets/stylesheets/style/mixins/theme/_radioBtn.scss
- app/assets/stylesheets/style/mixins/theme/_viewPage.scss
- app/views/member_tests/pass_form.slim
Я заменил select на чекбоксы и функционал отвалился.
upd:
поменял на radio - все починилось
> Added new custom checkboxes

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/footer.scss
- app/assets/stylesheets/form.scss
- app/assets/stylesheets/questions.scss
- app/assets/stylesheets/style/mixins/theme/_viewPage.scss
> Mobile view

- app/assets/stylesheets/pdf.scss
Keeps white space formatting in pdfs
https://trello.com/c/ompcqU4d/31-texts-in-pdf-with-line-wrapping
> #31 preserve whie space formatting for pdfs

- Gemfile.lock
- app/assets/stylesheets/pdf.scss
- app/models/member_test.rb
- app/views/member_tests/pdf.slim
https://trello.com/c/SLIjTN0n/32-changing-number-of-answers-in-pdf-depends-of-number-of-questions
> #32 dynamic number of answer cells for pdf

- app/views/members/show.slim
https://trello.com/c/HLbLOZiu/34-make-this-page-more-attractive
> member page styling ifx

- app/assets/stylesheets/table.scss
- app/views/member_tests/index.slim
- app/views/member_tests/show.slim
- app/views/members/index.slim
- app/views/members/show.slim
- app/views/tests/index.slim
Had to remove fixed table layout and adjusted other tables because of it
https://trello.com/c/3wqDwPYU/35-add-regenerate-function
> regenerate on member page fix + adjusted column widths

- app/views/member_tests/pdf.slim
https://trello.com/c/SLIjTN0n/32-changing-number-of-answers-in-pdf-depends-of-number-of-questions
> #pdf answer index fix

- app/assets/stylesheets/questions.scss
- app/views/member_tests/show.slim
https://trello.com/c/wozoOGkh/36-add-test-and-member-links-on-member-test-show-page
> add links to member test show page

- app/assets/stylesheets/pdf.scss
- app/views/member_tests/pdf.slim
https://trello.com/c/Q3OE8VfI/37-%D0%B2-%D0%BF%D0%B4%D1%84-%D1%83%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%BE%D1%81-%D1%81%D1%82%D1%80%D0%BE%D0%BA-%D0%B2-%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%B0%D1%85
> Keep formatting & align answers

- app/assets/stylesheets/pdf.scss
- app/controllers/member_tests_controller.rb
- app/views/member_tests/pdf.slim
https://trello.com/c/Uz0dfr0W/39-reduce-font-size-for-pdf-by-2
> Reduced font size for pdf

- app/assets/stylesheets/style/mixins/theme/_buttons.scss
- app/assets/stylesheets/table.scss
- app/controllers/member_tests_controller.rb
- app/views/member_tests/index.slim
https://trello.com/c/Q5Ladqb5/38-add-scopes-to-member-tests
> adds status filters to member tests

- app/assets/stylesheets/navbar.scss
- app/assets/stylesheets/style/mixins/theme/_buttons.scss
- app/assets/stylesheets/table.scss
- app/controllers/matrixes_controller.rb
- app/controllers/test_groups_controller.rb
- app/controllers/tests_controller.rb
- app/models/company.rb
- app/models/test.rb
- app/models/test_group.rb
- app/views/layouts/_navbar.slim
- app/views/matrixes/index.slim
- app/views/member_tests/index.slim
- app/views/members/index.slim
- app/views/test_groups/_form.slim
- app/views/test_groups/edit.slim
- app/views/test_groups/index.slim
- app/views/test_groups/new.slim
- app/views/test_groups/show.slim
- app/views/tests/_form.slim
- app/views/tests/index.slim
- app/views/tests/show.slim
- config/routes.rb
- db/migrate/20200911140139_create_test_groups.rb
- db/migrate/20200914142535_add_columns_to_test.rb
- db/schema.rb
https://trello.com/c/zsMQtF74/40-xxx
> Added test groups

- app/assets/stylesheets/table.scss
- app/controllers/test_groups_controller.rb
- app/views/layouts/_matrix.slim
- app/views/test_groups/_form.slim
- app/views/test_groups/index.slim
- app/views/test_groups/show.slim
- db/migrate/20200924120941_add_position_to_test_groups.rb
- db/schema.rb
https://trello.com/c/TLsTWrYp/51-add-positions-to-testgroups
> Added position to test_groups

- app/assets/stylesheets/table.scss
- app/views/member_tests/index.slim
- app/views/member_tests/show.slim
https://trello.com/c/tbZ6ZW12/44-member-test-show-page-link-bug
> Member test url bug fix

- app/views/members/show.slim
https://trello.com/c/PJtL7gR8/52-add-delete-action-to-member-show-page
> Added delete action to member show page

- app/controllers/member_tests_controller.rb
https://trello.com/c/J8P6GqS9/50-member-tests-table
> Improved member tests ordering

- app/controllers/member_tests_controller.rb
https://trello.com/c/7UY7TJPc/48-default-member-test-scope-draft
> Changed default scrope to draft

- app/controllers/tests_controller.rb
https://trello.com/c/yw09rXcC/49-tests-table
> Updated tests table ordering

- app/views/member_tests/index.slim
- app/views/member_tests/show.slim
https://trello.com/c/xI9rlDqN/47-member-tests-proper-test-name
> Improved test naming for member test pages

- app/assets/stylesheets/table.scss
- app/views/members/index.slim
- app/views/test_groups/index.slim
- app/views/tests/index.slim
https://trello.com/c/vTj4JhFP/45-members-table
> Member table improvements

- app/assets/stylesheets/questions.scss
https://trello.com/b/QXBsMI3f/levi-tests
> Test question answer wrapping fixed

- app/controllers/matrixes_controller.rb
- app/views/layouts/_navbar.slim
- app/views/matrixes/index.slim
- app/views/tests/index.slim
- config/routes.rb
https://trello.com/c/n6Lxot5g/56-remove-matrix-link
> Matrix location change

- app/views/members/index.slim
https://trello.com/c/dAIn6r9Q/55-issue-with-current-test-on-members-table
> Fixed current test bug

- app/assets/stylesheets/questions.scss
- app/assets/stylesheets/table.scss
- app/views/tests/show.slim
https://trello.com/c/slOAAuiV/54-add-whole-info-on-test-show-page
> Test show page data fix

- app/views/members/index.slim
https://trello.com/c/VuOZ1z20/63-add-member-group-to-members-table
> Added member group to member table

- app/assets/stylesheets/table.scss
- app/views/layouts/_matrix.slim
- app/views/tests/show.slim
https://trello.com/c/Dg8gqrOe/59-on-tests-add-some-stats
> Extra matrix information for tests

- app/controllers/member_tests_controller.rb
- app/views/members/show.slim
https://trello.com/c/TCr8kyJm/62-member-show
> Add new member test from member page

- app/controllers/tests_controller.rb
- app/views/test_groups/show.slim
https://trello.com/c/ixgYkWez/61-test-group-show-page
> Add test from test group page

- app/views/member_tests/pdf.slim
- app/views/tests/show.slim
https://trello.com/b/QXBsMI3f/levi-tests
> Added test group to test header

- app/views/members/show.slim
https://trello.com/c/A7Y2PDMP/58-add-summ-of-values-to-member-page-same-as-on-public-page
> Added sum of value to member show page
